language: node_js
node_js:
  - "10.15.3"
install:
  - npm install
script:
  - npm run build # Generate docs
deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep builded pages
  skip-cleanup: true
  # Directory where your generated files are located
  local_dir: docs
  # Github security/auth token
  github-token: $GITHUB_TOKEN
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  target_branch: docs
  on:
    # Which branch on commit/push will trigger deployment
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always